### PR TITLE
Added flags to disable hitscan decals

### PR DESCRIPTION
**Pull request by DaZombieKiller**
Added FHF_NOIMPACTDECAL for LineAttack in ACS, as well as +NODECAL and +FORCEDECAL for decorate

### CODE REVIEW

**Comment by MajorCooke** [comment]
I wonder why this hasn't been accepted yet?

**Comment by coelckers** [comment]
The main reason is that I'm not convinced about the FORCEDECAL flag. The rest is ok but that is doing things I consider improper.

**Comment by DaZombieKiller** [comment]
In that case, would you like me to remove FORCEDECAL?

**Comment by coelckers** [comment]
After reviewing this, I decided to keep both flags after all.

**Comment by DaZombieKiller** [comment]
Awesome

**Pull request merged**
