### PR TITLE
sv_fastweapons extension

### PR DESCRIPTION
**Pull request by marrub--**
makes 0-tic frames unaffected by sv_fastweapons 3 (which acts as sv_fastweapons 1 does otherwise)

### CODE REVIEW

**Comment by Edward850** [comment]
This is a 0tic lockup waiting to happen.

**Comment by MajorCooke** [comment]
It'd be better if this was something like sv_fastweapons 3 and 4, on a side note.

**Comment by edward-san** [comment]
> This is a 0tic lockup waiting to happen.

Why? ```psp->tics = (state->GetTics() != 0)``` makes sure that non-zero tics are mapped exclusively to 1 and zero tics to 0, so the chances for having 0tic lockups should be the same as normal speed weapon.

**Comment by marrub--** [comment]
Put the changed code into sv_fastweapons 3 and 4.

**Comment by Edward850** [comment]
@edward-san In the now tagged "sv_fastweapons 4", if you have a state cycle with functions only 0 tic frames, all frames in that cycle will have a tic of 0. Thus, an infinite loop.

**Comment by marrub--** [comment]
To be honest, fastweapons 4 is not exactly needed, since fastweapons 3 is already ridiculously fast.

**Pull request merged**
