### PR TITLE
QF_SCALEDOWN for A_QuakeEx

### PR DESCRIPTION
**Pull request by MajorCooke**
- Causes the quakes to smoothly fade out instead of just stopping hard. QF_SCALEUP will be coming next.

### CODE REVIEW

**Comment by coelckers** [comment]
I think this needs some cleanup before it's ready for production.

The mess of variables used to pass around the quake info is extremely unwieldy, it might be better to use a struct for this. Also, put the FLOAT2FIXED inside QuakePower if you do not need a float result anywhere.

**Comment by MajorCooke** [comment]
Tried that, it didn't work.

Can you help me with the struct? I'll take a look into it but I need some ideas on how I should use it.

**Comment by MajorCooke** [comment]
Aaand, struct done! Wow, you're right! Those structs are going to save me so much headache!

**Comment by MajorCooke** [comment]
Okay. All done, now a struct is passed for convenience. And, you're right Graf. It's a giant pain to have to adjust all the individual functions.

**Pull request merged**
