### PR TITLE
Added detection for endless loops in states

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
Tested on [Napalm Launcher](http://realm667.com/index.php/en/component/docman/?task=doc_download&gid=266) from Realm 667 Repository (Armory, Other Sources / Styles) via `summon Gasoline` command in console.

### CODE REVIEW

**Comment by coelckers** [comment]
I'm not sure what this is supposed to accomplish, the 'prevtics' seems to make this only trigger endless loops where all states have the same length.

**Comment by alexey-lysiuk** [comment]
In the mentioned Napalm Launcher, there are the following code:
```
ACTOR Gasoline : Ammo
{
   // ... not important ... 
   States
   {
   Spawn:
      GASO A 0
      Loop
   }
}
```
The change is preventing the game from hanging in the infinite loop in case above and the error message will be displayed. Mod authors will no longer blame engine for this, but will be aware of their poor written DECORATE's.

**Comment by coelckers** [comment]
That's only one special case of an empty loop. Why did you implement this so that multistate loops aren't caught?

**Comment by alexey-lysiuk** [comment]
I didn't encounter such an error, so I was not aware of it.

**Comment by Blzut3** [comment]
Like Graf's interpretation, it looks to me like this would trigger even if the state has a delay.  The specific case of looping a 0 tic state with no action function is probably something can can be identified statically during FStateDefinitions::FinishStates.

**Comment by Gaerzi** [comment]
Or you could count state transitions and reset that counter every tic. If you get billions of state changes for a single actor in a single tic, it's probably safe to assume bad coding is involved.

**Comment by Blzut3** [comment]
Declining this pull request since there have been no updates and it's clear that this is not the way to go about this.

**Pull request closed without merging**
