### PR TITLE
- Added A_CheckBlock

### PR DESCRIPTION
**Pull request by MajorCooke**
(state noblock, state blockline, state blockactor…[, int flags[, ptr]]).
- Added CLOFF_JUMPOBSTACLES macro to constants.txt.

### CODE REVIEW

**Comment by crimsondusk** [comment]
This seems like a very complicated function. Are all those flags seriously needed or did you just add them for the sake of adding them?

**Comment by MajorCooke** [comment]
I need them big time. Allow me to explain... 

The biggest reason I need them is because there's no way currently for 'transient' actors (ones without any sort of blocking) to properly check and see if they have room to spawn something. For example, A_SpawnItemEx grabs the spawning actor's properties and performs a check with its flags to see if it's solid or not, and I need A_SpawnItemEx to make sure they have a place to spawn them legitimately. Otherwise, doing actor checking becomes a hassle because we have to turn off THRU flags or make the actor solid in order to spawn it properly.

But wait, that's not all. Another reason I need the flag is because if I have an actor that, depending on circumstances, may or may not care about moving through other actors such as species, I dont want them to exclude all actors from checking blocking, such as if they were to get stuck. I will use it to ensure the actor excludes species actors and can 'get the go-ahead' to jump, knowing its safe to do whatever it is that it wants to.

I NEVER add things unless I see a use for them. Trust me on this. I need all of these for something I'm working on, and I can't proceed further without it.

**Comment by MajorCooke** [comment]
A shorter explanation is to allow actors that aren't ever meant to become blocking, stay non blocking without the need to change flags. Even on 0 tic switches, it can still interrupt things and cause missiles to explode on the actors as one example.

**Comment by MajorCooke** [comment]
Closing this for an updated version due to merge conflicts.

**Pull request closed without merging**
