### PR TITLE
Static added to Zscript CreateCeiling

### PR DESCRIPTION
**Pull request by gwHero**
Keyword 'static' was missing in base.txt for CreateCeiling.
[base.txt](https://github.com/rheit/zdoom/files/1502973/base.txt)

### CODE REVIEW

**Comment by gwHero** [comment]
Something went wrong with the pull request, only 1 line should be changed.

**Comment by alexey-lysiuk** [comment]
You should do pull request to [coelckers/gzdoom](https://github.com/coelckers/gzdoom)

**Comment by gwHero** [comment]
Hi,

yeah, seem to struggle with Github (not very used to it). I had Graf's fork
selected, but when I choose "new pull request", it switches to Rheit\ZDoom.

**Comment by alexey-lysiuk** [comment]
First you need to commit and push changes to a new branch. Then press `New pull request` button and click on _compare across forks_ link.
After then you can select proper base and compare/head forks.

**Comment by gwHero** [comment]
I think I finally did it right.. god, making the change was only a minute
work, but github almost made me throwing my laptop out of the window :)

Thanks for the help.

**Pull request closed without merging**
