### PR TITLE
Small improvements for random spawner

### PR DESCRIPTION
**Pull request by alexey-lysiuk**

### CODE REVIEW

**Comment by MajorCooke** [comment]
I think this could be let off with a warning instead, if it isn't. Otherwise, some mods may break.

**Comment by alexey-lysiuk** [comment]
Could you please point me to the mentioned line of code?

**Comment by MajorCooke** [comment]
I should have stated, I haven't tested this out yet, but in case it does prevent startup you might want to consider it. As your committ suggests "error message", I assumed that may have prevented startup from occurring.

**Comment by alexey-lysiuk** [comment]
The error message here is just a red colored text printed to the console.

**Comment by MajorCooke** [comment]
Oh! Well alrighty then!

**Pull request merged**
