### PR TITLE
Add /usr/local/share/zdoom to search paths, too, for FreeBSD sake

### PR DESCRIPTION
**Pull request by kevans91**
Not entirely an insane proposition.

### CODE REVIEW

**Comment by coelckers** [comment]
"/usr/local/share/zdoom" or "/usr/local/share/" GAMENAME ?

I assume the latter would be correct but I need clarification.

**Comment by kevans91** [comment]
Ah, fair point. The latter would be preferred, then. =P

Kyle Evans, Web/Database Developer
College of Engineering, Kansas State University
kevans91@ksu.edu    (785) 532-4643    30 Seaton Hall

**Comment by edward-san** [comment]
I'm curious to know why not also `"/usr/local/share/games/" GAMENAME`, too..

**Comment by kevans91** [comment]
Mostly because I don't have a justification for this case. =P It's a good
idea, but given I can't immediately identify a place where this happens
(and this seems to have not necessarily come up before), I've omitted it.

On Mon, Aug 22, 2016 at 10:21 AM, Edoardo Prezioso <notifications@github.com

**Comment by edward-san** [comment]
:+1:

**Comment by kevans91** [comment]
Sorry, I've had a change of heart one last time...soon will be adding @edward-san's suggestion (because it's sensible, and one could wish for such a setup), but also converting GAMENAME to GAMENAMELOWERCASE and also adding SHARE_DIR GAMENAMELOWERCASE to FileSearch.Directories.

If wished, I can go ahead and re-open this with a squashed history.

**Comment by kevans91** [comment]
Will be re-opening this later- a better idea has emerged.

**Pull request closed without merging**
