### PR TITLE
GCC and Clang compilation errors and one warning for floatcvt branch

### PR DESCRIPTION
**Pull request by edward-san**

### CODE REVIEW

**Comment by edward-san** [comment]
Requires feeback from @alexey-lysiuk to check if the fix works also for Mac.

**Comment by edward-san** [comment]
I'll have to revert the 'Remove the unneeded headers' commit, since the most recent commits in the floatcvt branch has made it completely useless. Also I have to amend the other commit with new error fixes, so don't do anything unless I finished rebasing this.

**Comment by edward-san** [comment]
It's ready now. No OSX-specific feedback is required anymore.

**Comment by alexey-lysiuk** [comment]
Finally I have a possibility to check this pull request.
Changes themselves are OK. I didn't get it why `mo->Angles.Yaw.Normalized360().Degrees` was used in `c_cmds.cpp` instead of just `mo->Angles.Yaw.Degrees`, but it's no so important.
However OS X will require additional changes because of a few name clashes with system's framework. I'll make a PR when this one will be merged in.

**Comment by edward-san** [comment]
```mo->Angles.Yaw.Normalized360().Degrees``` is used because the command ```currentpos``` prints the player's angle in the ```[0,360[``` range.

**Comment by edward-san** [comment]
sorry, it seems I messed with the branch again... if I can't solve this, I'll have to close it and recreate from scratch.

**Comment by edward-san** [comment]
Okay, managed to solve the problems. Should be okay to merge now.

**Pull request merged**
