### PR TITLE
[internal] Introduce FNetCommand, for code flexibility with Zandronum.

### PR DESCRIPTION
**Pull request by edward-san**

### CODE REVIEW

**Comment by coelckers** [comment]
What's the benefit here?
You have to tell a bit more than 'for flexibility with Zandronum.'

**Comment by edward-san** [comment]
Indeed, I'll add more context. FinalizeCommand() could be modified by zandronum to execute immediately the command (i.e. call Net_DoCommand) without passing to the specials buffer (for example because zandronum doesn't use the DEM_ commands, except in the demos).

The actual approach showed its problems during zandronum's code upgrade. See for example this ticket: http://zandronum.com/tracker/view.php?id=424 , even though the centerview code was upgraded from zdoom, the fix didn't work, until I discovered that zandronum's centerview code was kept the same as before.

Zandronum's fix calls Net_DoCommand directly, but then a new problem arises: if the DEM_ command contains additional parameters, a custom BYTE buffer must be created from scratch and then the data were pushed manually inside, as seen here: https://bitbucket.org/Torr_Samaho/zandronum/src/b7cc4d70fad790bddb2e0e4efd981073e8ab7273/src/sv_main.cpp?at=default&fileviewer=file-view-default#sv_main.cpp-4159.

The new code could help dealing with this, by making sure all the DEM_ command instances would receive the same treatment.

I hope I was clear with it.

**Comment by edward-san** [comment]
Actually I'm thinking about a simpler approach for this. Hence, please hold it before doing anything.

**Comment by edward-san** [comment]
Done. Maybe in the future, the DEM_ system should be replaced by classes with the ctor parameters matching the buffer parameters, in order to add type safety. For example:

```c++
Net_NewCommand(Changemap2 (atoi(argv[2]), argv[1]));
```

which could also 'absorb' ```Net_FinalizeCommand```.

**Comment by edward-san** [comment]
Urgh, I guess I should go with the class approach. Adding Net_FinalizeCommand on each thing can be error prone.

**Comment by Blzut3** [comment]
This implementation does seem to lack any benefit for ZDoom.  I've suggested to edward-san that the same goal (allow Zandronum to finalize a command) could be obtained by having FNetCommand be an object which implements Net_Write*.  If the class methods were marked static (but still called against the stack object) in ZDoom this would produce zero over head and just be a code style change, but Zandronum would be free to reimplement FNetCommand and utilize the destructor.

edward-san's suggestion to use separate classes for each command and having stronger typing seems like a good idea, but I don't see how that would be done sanely without a code generator like what Dusk is writing for Zandronum, and that seems overkill for ZDoom.

**Pull request closed without merging**
