### PR TITLE
Screen Melting Issue

### PR DESCRIPTION
**Pull request by NiTROACTiVE**
Whenever the screen melts to a different screen/level, it goes black, meaning you can't see the last image of the level/screen as the screen melts when you complete a level. There's even times where the screen will freeze to that image until it's done melting.

This post from a thread I posted about this problem contains information on what should be done to fix this when it comes to the code:
https://www.doomworld.com/vb/post/1723774

### CODE REVIEW

**Comment by alexey-lysiuk** [comment]
This PR should go to [GZDoom repository](https://github.com/coelckers/gzdoom).

**Comment by NiTROACTiVE** [comment]
@alexey-lysiuk  For some reason, I was redirected to the ZDoom repository when I made my pull request. I also just realized this now.

**Comment by alexey-lysiuk** [comment]
Nevermind, I have just pushed the fix to GZDoom. The code from the screenshot in that DW topic was a bit lame: idea is correct but implementation is not.

**Comment by alexey-lysiuk** [comment]
Graf, could you please close this PR? Notification on each commit to GZDoom `master` branch is rather annoying.

**Comment by coelckers** [comment]
This has already been addressed and this PR was for the wrong repo, essentially it pulls the entire GZDoom code base into ZDoom.

**Pull request closed without merging**
