### PR TITLE
[DEC] Sound channel decorate properties

### PR DESCRIPTION
**Pull request by DaZombieKiller**
Added the following decorate properties:
SeeSoundChannel, AttackSoundChannel, PainSoundChannel, CrushPainSoundChannel, DeathSoundChannel, ActiveSoundChannel, BounceSoundChannel, WallBounceSoundChannel, Inventory.UseSoundChannel and Inventory.PickupSoundChannel.

### CODE REVIEW

**Comment by Blzut3** [comment]
Original thread for reference: http://forum.zdoom.org/viewtopic.php?f=34&t=48992

I don't care much for this method of going about things.  Besides adding a pretty significant amount of bloat to the AActor structure, the current state of DECORATE doesn't allow named constants in properties (as far as I can remember at least and your patch doesn't give me any reason to believe otherwise) and I don't think we want to add APIs that use magic numbers.

Given the original motivation (defining a sound as a voice clip) I wonder if it would be adequate to have an option in SNDINFO to hint what channel the sound should be played on?  No idea how that would play out with S_IsActorPlayingSomething.  Graf, your thoughts?

**Comment by DaZombieKiller** [comment]
I certainly agree that this probably isn't exactly the best way of handling the situation. I was hoping to use the const() expression but then realized that this wasn't in yet: http://forum.zdoom.org/viewtopic.php?f=34&t=31516

A SNDINFO option could work, guess we'll wait for Graf's response.

**Comment by crimsondusk** [comment]
The SNDINFO option indeed sounds more flexible to me. Then we wouldn't need a new actor property for each and every use case.

**Comment by DaZombieKiller** [comment]
Alright, let's discard this pull request for now, somewhere down the line when I have some more free time I'll look into re-doing this as a SNDINFO option.

Blzut3: Since there are multiple hardcoded cases where specific channels are used, would you consider it a more elegant solution if there were SNDINFO properties like "spawnchannel", "seechannel", etc?

**Pull request closed without merging**
