### PR TITLE
WARPF_USETID, Warp enum in ZDoom range

### PR DESCRIPTION
**Pull request by DaZombieKiller**

### CODE REVIEW

**Comment by Blzut3** [comment]
http://forum.zdoom.org/viewtopic.php?f=2&t=49220

Was this ever compiled before submission?

**Comment by MajorCooke** [comment]
I can't even tell whose stuff did what between Graf consolidating the function and DaZombieKiller's submission changes, all I know of is, it's broken.

**Comment by Blzut3** [comment]
SingleActorFromTID has been a static function in p_acs.cpp since 2010 meaning it can't be called from thingdef_codeptr.cpp.  This leads me to believe that DaZombieKiller is submitting things without compiling them.

**Comment by MajorCooke** [comment]
Well its been taken care of now.

**Comment by DaZombieKiller** [comment]
Time for me to go yell at marrub then, this was a commit I did on his behalf

**Comment by Blzut3** [comment]
@DaZombieKiller NEVER submit any patches to us that you haven't personally compiled **and** tested.  I don't care how safe it looks or who told you to do it.

**Pull request merged**
