### PR TITLE
- Added lambda feature to FString::(Strip|Replace)Chars.

### PR DESCRIPTION
**Pull request by edward-san**
Use it in the other (Strip|Replace)Chars methods to show how it would work.

### CODE REVIEW

**Comment by coelckers** [comment]
Does this even work with the template function in the source file and not the header?

**Comment by edward-san** [comment]
It compiled fine for me (gcc 5 and 6, clang). What about MSVC?

**Comment by edward-san** [comment]
Whoops, you're right. If I try using in a different source than zstring.cpp, indeed it errors out. I'll try to fix it.

**Comment by edward-san** [comment]
Fixed, should work now.

**Pull request merged**
