### PR TITLE
Fix uncleared buffer when upscaling the cursor

### PR DESCRIPTION
**Pull request by dpjudas**

### CODE REVIEW

**Comment by Blzut3** [comment]
You can use memset on TArrays.

**Comment by dpjudas** [comment]
This isn't a time critical function. Any kind of clear will do. Besides, the compiler knows the exact length I'm clearing with, so if its more efficient to do it with a memset it will optimize it into just that.

**Comment by coelckers** [comment]
Any self respecting compiler would generate the same or almost the same code for both.

**Comment by Blzut3** [comment]
I wasn't talking about performance.  Maybe I'm weird and just find memset more readable than the manual variant.  Whatever.

**Pull request merged**
