### PR TITLE
Decorate tweaks

### PR DESCRIPTION
**Pull request by ZzZombo**
- Fixed discrepancy in master handling between Decorate and ACS.
- Added an option for A_DamageX() functions to work with either percentage of victim's current health or maximum health.
- Minor tweaks to the code.

### CODE REVIEW

**Comment by coelckers** [comment]
There's two issues here:

The discrepance with master is intentional. DECORATE references the actual master variable, ACS the actor to be considered a master. Since that's the main change here I won't merge this.

The second problem is the line ending issue with thingdef_codeptr. This change affects too many lines in that file and is a problem for merging the scripting branch.

The rest is too inconsequential to bother with.

**Comment by ZzZombo** [comment]
I don't really follow you, do you mean it's a well-thought design you can have two different masters at the same time?

**Comment by Edward850** [comment]
I don't think you really get how old ZDoom is.

**Comment by coelckers** [comment]
This isn't about having two different masters, but about what semantics are applied here. The DECORATE code references the master member variable with no second guessing if a player may own the monster. If this gets changed, things might break horribly. 

ACS on the other hand returns what owns the current monster and allows some interpretation. Decorate cannot afford this because AAPTR_MASTER and the AActor::master variable MUST always refer to the same information. This is a very volatile matter.

**Comment by ZzZombo** [comment]
Implying it answers my question.

09.02.2015, 06:53, "Edward Richardson" <notifications@github.com>:

**Comment by Edward850** [comment]
Aside from Graf explaining it anyway, I was referring to the point that you can't go in and change something like that with 15 years worth of mods. You're going to break something with such a change.
Granted, that's 3 years for pointer control, but that's still a lot of time.

**Pull request closed without merging**
