### PR TITLE
Added option to control dynamic loading of OpenAL

### PR DESCRIPTION
**Pull request by alexey-lysiuk**
Dynamic loading is enabled by default, set DYN_OPENAL to OFF to link with static or dynamic library

### CODE REVIEW

**Comment by coelckers** [comment]
Is there any reason why this is needed?

(And sorry for the late response, the notification mail for this one ended in my spam folder.)

**Comment by alexey-lysiuk** [comment]
Yes, it's not possible to link to OpenAL-Soft implementation statically. The current implementation tries to load the framework from some predefined paths no matter what.
I will update PR if you decided to merge it in.

**Comment by coelckers** [comment]
"Yes, it's not possible to link to OpenAL-Soft implementation statically."

The 'real' OpenAL seems to be a bit strange. That's why I was forcing dynamic loading in the first place. What I do not understand is, is this about allowing dynamic loading where it wasn't possible or about preventing dynamic loading where it was already being used?

**Comment by alexey-lysiuk** [comment]
It's about an ability to link with a particular OpenAL implementation statically.
On OS X there are two well known implementation: Apple's framework and OpenAL-Soft. For GZDoom for OS X I'm using OpenAL-Soft because it has more features than basic Apple's framework (it doesn't have any features outside of OpenAL spec).
Why am I using static linking? Because I want to avoid any troubles with custom dynamic libraries or frameworks of unknown version installed by some other software.
With the introduction of mandatory dynamic loading for OpenAL I'm no longer able to control this. That's why I made this pull request.
If you think it's not feasible, I'll understand.

**Comment by coelckers** [comment]
No problem. I was just wondering because on Windows I added run-time linking for the same reason (the inability to use a custom DLL if the 'real' OpenAL got installed because for some reason it then always picks the system.installed version.)

**Pull request closed without merging**
