### PR TITLE
[2.4.0] Player name changes don't register

### PR DESCRIPTION
**Pull request by SashaTheRed**
In the Player Setup menu, typing a name and pressing Enter doesn't do anything like it did in the old versions. When making a fresh config, I had to use the _name_ command in the console.

Also, I think I've done something terribly wrong with this pull request. Never done one before. I just wanted to report this bug here.

### CODE REVIEW

**Comment by coelckers** [comment]
This PR is dirty. I wasn't even able to find the relevant thing inside all the stuff that it pulls in. Please redo in a clean fashion.

**Comment by SashaTheRed** [comment]
I don't even know how else you want me to report the bug - on the DRDTeam forum, you link us to the pull request page for reporting bugs. No other instructions.

**Comment by coelckers** [comment]
The problem here is that the pull request not only includes a fix but the entire master branch which you want to merge into 2.4.0. That's not how things should be done.

A pull request is supposed to contain only the commits relevant to what you want to get added. So either make a PR for master or rebase your own commit

**Comment by SashaTheRed** [comment]
I don't have anything to add besides the actual problem, and I can't find any issue tracker. The link in this thread - https://forum.drdteam.org/viewtopic.php?f=206&t=7442 - leads to the pull request page. I don't really know how to make a pull request, but I have no other way of reporting the bug, eh?

**Comment by alexey-lysiuk** [comment]
https://mantis.zdoom.org/

**Comment by SashaTheRed** [comment]
Thanks.

**Pull request closed without merging**
